#!/usr/bin/env python3
# scripts/concat_compiler_source.py
#
# Produce ONE single-module Adder source that is the whole self-hosted
# compiler — lexer.ad + parser.ad + codegen.ad — concatenated in dependency
# order, with their intra-compiler `from compiler.X import (...)` blocks
# stripped.
#
# WHY: the self-hosted lexer/parser is SINGLE-MODULE. It does NOT execute
# `import`; the host (Python) build resolves `from compiler.X import (...)`
# at compile time, but the Adder-in-Adder lexer/parser would choke on (or
# at best must ignore) those statements. To compile the WHOLE compiler with
# itself (the self-host fixpoint, task #154) we first need the three modules
# fused into one translation unit with the cross-module imports removed —
# every symbol then resolves within the single concatenated namespace.
#
# This is sound because (verified): the three modules share NO duplicate
# top-level symbol, declare NO `extern def`, and the only imports are the
# intra-compiler `from compiler.{lexer,parser} import (...)` blocks. So
# stripping those blocks and concatenating in dependency order (lexer, then
# parser, then codegen) yields a self-consistent single module.
#
# Usage:
#   python3 scripts/concat_compiler_source.py [-o OUT.ad] [--with-driver]
# Default output: build/selfhost/whole_compiler.ad
#
# With --with-driver, the fusion ALSO includes elf_emit.ad (the ELF image
# emitter) and APPENDS adder/compiler/fused_driver_main.ad — a driver
# `main` that reads /src/input.ad, runs the full
# lex -> parse -> codegen -> elf_emit pipeline, and hex-dumps the emitted
# ELF over stdout (via codegen.ad's inline `__syscallN` builtins). This
# turns the library-of-functions into a SELF-CONTAINED, RUNNABLE compiler
# binary — the artifact the stage1==stage2 fixpoint (test_selfhost_fixpoint.sh)
# compiles with itself.
#
# Deterministic: the output is a pure function of the input files.

import os
import sys

PROJ_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COMPILER_DIR = os.path.join(PROJ_ROOT, "adder", "compiler")

# Dependency order: lexer defines tokens, parser consumes them, codegen
# consumes the AST. codegen.ad references parser+lexer symbols, parser.ad
# references lexer symbols — so lexer FIRST, codegen LAST.
MODULES = ["lexer.ad", "parser.ad", "codegen.ad"]

# Extra module fused in ONLY for --with-driver: the ELF image emitter the
# driver `main` calls (elf_emit_image). It imports from compiler.codegen,
# whose `from compiler.X import (...)` block is stripped like the others.
DRIVER_EXTRA_MODULES = ["elf_emit.ad"]

# Appended verbatim (NOT import-stripped — it has no compiler imports) for
# --with-driver: the driver `main` that drives the whole pipeline.
DRIVER_MAIN = "fused_driver_main.ad"


def strip_compiler_imports(text):
    """Remove every `from compiler.X import (...)` block.

    The block spans from a line beginning with `from compiler.` (after
    optional leading whitespace; these are all top-level so unindented)
    through the line whose stripped content is exactly `)`. A single-line
    `from compiler.X import a, b` (no paren) is dropped as one line.
    Returns the stripped source text.
    """
    out_lines = []
    lines = text.split("\n")
    i = 0
    n = len(lines)
    while i < n:
        line = lines[i]
        stripped = line.lstrip()
        if stripped.startswith("from compiler."):
            # Parenthesised multi-line import: drop through the line that
            # is just `)`.
            if "(" in line:
                # Consume until the closing `)` line (inclusive).
                while i < n and lines[i].strip() != ")":
                    i += 1
                # Drop the `)` line too (if present).
                if i < n:
                    i += 1
                continue
            # Single-line `from compiler.X import a, b` — drop just it.
            i += 1
            continue
        out_lines.append(line)
        i += 1
    return "\n".join(out_lines)


def main(argv):
    out_path = os.path.join(PROJ_ROOT, "build", "selfhost", "whole_compiler.ad")
    with_driver = False
    args = argv[1:]
    j = 0
    while j < len(args):
        if args[j] in ("-o", "--out"):
            out_path = args[j + 1]
            j += 2
        elif args[j] == "--with-driver":
            with_driver = True
            j += 1
        else:
            sys.stderr.write(
                "usage: concat_compiler_source.py [-o OUT.ad] [--with-driver]\n"
            )
            return 2

    modules = list(MODULES)
    if with_driver:
        modules += DRIVER_EXTRA_MODULES

    chunks = []
    header = (
        "# GENERATED by scripts/concat_compiler_source.py — do not edit.\n"
        "# Single-module fusion of the self-hosted compiler:\n"
        "#   " + " + ".join(modules) + "\n"
        "# with intra-compiler `from compiler.X import (...)` blocks stripped.\n"
    )
    if with_driver:
        header += "# + appended driver main (" + DRIVER_MAIN + ").\n"
    chunks.append(header)

    for mod in modules:
        src_path = os.path.join(COMPILER_DIR, mod)
        with open(src_path, "r") as f:
            text = f.read()
        stripped = strip_compiler_imports(text)
        chunks.append("\n# ===== begin " + mod + " =====\n")
        chunks.append(stripped)
        chunks.append("\n# ===== end " + mod + " =====\n")

    if with_driver:
        drv_path = os.path.join(COMPILER_DIR, DRIVER_MAIN)
        with open(drv_path, "r") as f:
            drv_text = f.read()
        # The driver has no `from compiler.` imports, but strip defensively
        # so future edits can't sneak one in.
        drv_text = strip_compiler_imports(drv_text)
        chunks.append("\n# ===== begin " + DRIVER_MAIN + " =====\n")
        chunks.append(drv_text)
        chunks.append("\n# ===== end " + DRIVER_MAIN + " =====\n")

    fused = "".join(chunks)

    out_dir = os.path.dirname(out_path)
    if out_dir and not os.path.isdir(out_dir):
        os.makedirs(out_dir, exist_ok=True)
    with open(out_path, "w") as f:
        f.write(fused)

    nbytes = len(fused.encode("utf-8"))
    sys.stderr.write(
        "[concat] wrote %s (%d bytes, %d lines)\n"
        % (out_path, nbytes, fused.count("\n") + 1)
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
